[project]
name = "prokaryotes"
version = "0.1.0"
description = "Denizens of the primoridal soup"
requires-python = ">=3.12"
dependencies = [
    "aiofiles",
    "certifi",
    "elasticsearch[async]",
    "fastapi",
    "imapclient",
    "neo4j",
    "openai",
    "python-dotenv",
    "uvicorn",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--strict-markers --cov=prokaryotes"
testpaths = [
    "tests",
]

[tool.setuptools.packages.find]
include = ["prokaryotes*"]
